### ISSUE TITLE
Connection to SAP HANA failed [object Object] -- wrong provider for this platform?

### ISSUE THREAD

**Issue by abcox** [SAP/sap-hana-driver-for-sqltools#66]
['driver:saphana:error'] Connection to SAP HANA failed [object Object]
[1604076407670] ERROR (ls): Connecting error: {"code":-10709,"data":{"driver":"SAPHana","driverOptions":{}},"name":"DecoratedException"}
    ns: "conn-manager"
[1604076407671] ERROR (ext): ERROR: Error opening connection Connection failed (RTE:[1000013] wrong provider for this platform (address-redacted:30015)), {"code":-10709,"data":{"driver":"SAPHana","driverOptions":{}}}
    ns: "error-handler"

**Comment by ariel-bentu** [comment]
Hello abcox, can you please your connection details (of course omit/replace with xxx any sensitive info). Especially I suspect it has to do the port of the HANA instance (30015 sounds like a port).
Try to show both the info of the connection configuration of SQLtools and the source of the credentials (e.g. a service-key from HANA Service)
thanks

**Comment by meakgoz2** [comment]
Hi ariel,

I have exactly the same problem, so instead of duplicating with another issue decided to write here.  
I am trying to connect to my SAP HANA Service
I have created a service key in my SAP HANA Schemas & HDI Containers service and trying to use the necessary information from there.  

![image](https://user-images.githubusercontent.com/31985335/98910621-b93df480-24c3-11eb-9c39-baff7824189c.png)

I copy the `host` field from the key as is to the `HANA Server*`.  
To the `Server Port*` I have written `22093`.  
Schema I copied over as is from the key.
For username and password, I tried both combinations, i.e., once with `hdi_user` & `hdi_password` pair and once with `user` & `password` pair.   
I have the default connection options and leave the `SSL Trust Store` empty.

Eventually I get the following log in the console when I try to connect:
```
[1605166597182] INFO  (ls): Connection instance created for sitDM.
    ns: "conn-manager"
['driver:saphana:error'] Connection to SAP HANA failed [object Object]
[1605166597250] ERROR (ls): Connecting error: {"code":-10709,"data":{"driver":"SAPHana","driverOptions":{}},"name":"DecoratedException"}
    ns: "conn-manager"
[1605166597252] ERROR (ext): ERROR: Error opening connection Connection failed (RTE:[1000013] wrong provider for this platform (<host from the service key here>:22093)), {"code":-10709,"data":{"driver":"SAPHana","driverOptions":{}}}
    ns: "error-handler"
```

**Comment by abcox** [comment]
> Hello abcox, can you please your connection details (of course omit/replace with xxx any sensitive info). Especially I suspect it has to do the port of the HANA instance (30015 sounds like a port).
> Try to show both the info of the connection configuration of SQLtools and the source of the credentials (e.g. a service-key from HANA Service)
> thanks

Hello Ariel. Thanks for your reply. My connection settings (.vscode/settings.json) originally looked like:

{
    "sqltools.connections": [
        {
            "connectionTimeout": 30,
            "hanaOptions": {
                "encrypt": true,
                "sslValidateCertificate": true,
                "sslCryptoProvider": "openssl"
            },
            "previewLimit": 50,
            "driver": "SAPHana",
            "name": "xxx",
            "server": "xxx",
            "port": xxx,
            "database": "xxx",
            "username": "xxx",
            "password": "xxx"
        }
    ]
}

Since this, I have tried with setting the encrypt and sslValidateCertificate to false, and getting the following log:

[1605196820767] INFO  (ls): Connection instance created for xxx.
    ns: "conn-manager"
[1605196821259] ERROR (ls): Connecting error: {"code":257,"data":{"driver":"SAPHana","driverOptions":{}},"name":"DecoratedException"}
    ns: "conn-manager"
[1605196821261] ERROR (ext): ERROR: Error opening connection sql syntax error: line 1 col 12 (at pos 12), {"code":257,"data":{"driver":"SAPHana","driverOptions":{}}}
    ns: "error-handler"

BTW... I have been successful to connect to this instance from java work via jdbc, so I know this would work if all things with extension and its config were in order.

Thanks for your attention.

**Comment by abcox** [comment]
My latest config seems closest:

`
{
    "sqltools.connections": [
        {
            "connectionTimeout": 30,
            "hanaOptions": {
                "encrypt": false,
                "sslValidateCertificate": false,
                "key": "xxx"
            },
            "previewLimit": 50,
            "driver": "SAPHana",
            "name": "xxx",
            "server": "xxx",
            "port": xxx,
            "database": ""
        }
    ]
}
`

Log entries:

[1605197811989] INFO  (ls): Connection instance created for xxx.
    ns: "conn-manager"
['driver:saphana:error'] Connection to SAP HANA failed [object Object]
[1605197812739] ERROR (ls): Connecting error: {"code":10,"data":{"driver":"SAPHana","driverOptions":{}},"name":"DecoratedException"}
    ns: "conn-manager"
[1605197812740] ERROR (ext): ERROR: Error opening connection authentication failed, {"code":10,"data":{"driver":"SAPHana","driverOptions":{}}}
    ns: "error-handler"

**Comment by ariel-bentu** [comment]
Hi,

Here are few things that may help:
1. The HANA driver is based on the open-source, and is supported by SAP (see [here](https://github.com/SAP/node-hdb#sap-support-for-hdb-and-saphana-client).
2. According to docu, and also if you try to install directly using `npm install @sap/hana-client` you get a message that Node.js v15 is not yet supported (`Node version v15.0.1 is unsupported by @sap/hana-client. Current supported versions are 8, 10, and 12`)
3. If this is the issue, try running vscode with a supported node version [see here](https://stackoverflow.com/questions/44700432/visual-studio-code-to-use-node-version-specified-by-nvm)
4. Assuming you are running with the supported, I have created a simple node.js code that tests a connection based on the @sap/hana-client only. 
```
const hana = require('@sap/hana-client')

const settings = {
    "sqltools.connections": [
        {
            "connectionTimeout": 30,
            "hanaOptions": {
                "encrypt": false,
                "sslValidateCertificate": false,
                "key": "xxx"
            },
            "previewLimit": 50,
            "driver": "SAPHana",
            "name": "xxx",
            "server": "xxx",
            "port": xxx, "database": ""
        }]
}

let credentials = settings["sqltools.connections"][0];

let connOptions = {
    HOST: credentials.server,
    PORT: credentials.port,
    UID: credentials.username,
    PWD: credentials.password
}

if (credentials.connectionTimeout && credentials.connectionTimeout > 0) {
    connOptions["CONNECTTIMEOUT"] = credentials.connectionTimeout * 1000;
}

connOptions = {
    ...connOptions,
    ...(credentials["hanaOptions"] || {}),
};

var conn = hana.createConnection(connOptions);

try {

    conn.connect(err => {
        if (err) {
            console.log("Connection to SAP HANA failed", err.toString());
            throw (err);
        }
        let schema = credentials.database;
        conn.exec("SET SCHEMA " + schema, err => {
            if (err) {
                throw (err);
            }

            console.log("Connection to SAP Hana succeeded!");

        });
    });

} catch (e) {
    console.log("Connection to SAP HANA failed" + e.toString());
}
```

to use it:
1. create a file with this code: e.g. test.js
2. update the "settings" variable in the code to match your settings 
3. run `npm install @sap/hana-client`
4. run `node test.js`

if this fails, then the problem is not in the hana-driver of sql-tools but directly in the hana-client driver - and we should move the support to there. if it succeeds, then please reply and we will try to think of the next step.

Ariel

**Comment by NouamaneTazi** [comment]
I have the same problem.
After trying your node.js code @ariel-bentu I get the error:
`{
  code: -10709,
  message: "Connection failed (RTE:[89006] System call 'connect' failed, rc=10060:A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond {{HOST}:30041} ({HOST}:30041))",
  sqlState: ''
}`

Thanks for your help.

**Comment by ariel-bentu** [comment]
Hello,
At this point, I ask the following:
- If connection is successful with the code above, and within SQL tools it fails - open an issue
- If connection fails with the code above, please do not open an issue here, but refer to [this](https://github.com/SAP/node-hdb#sap-support-for-hdb-and-saphana-client) repo and seek support there.

Thanks
